# Build-time generator for the reviewed worker deployment manifest.
# It hashes only files produced by the Worker Release build and writes a generated C# source file.
param(
    [Parameter(Mandatory)][string]$WorkerOutput,
    [Parameter(Mandatory)][string]$OutputPath
)
$ErrorActionPreference = 'Stop'
if (!(Test-Path -LiteralPath $WorkerOutput -PathType Container)) {
    throw "Worker output directory is missing: $WorkerOutput"
}

$root = [IO.Path]::GetFullPath($WorkerOutput)
. "$PSScriptRoot/worker-runtime-closure.ps1"
$files = @(Get-WorkerRuntimeFiles -Root $root)
if ($files.Count -eq 0) { throw 'Worker output contains no deployable files.' }

function Quote-CSharp([string]$Value) {
    # JSON string escaping is valid C# string-literal escaping for the reviewed paths,
    # hashes, and assembly identities generated here.
    return ($Value | ConvertTo-Json -Compress)
}

$entries = [Collections.Generic.List[object]]::new()
foreach ($file in $files) {
    $relative = $file.RelativePath
    $mvid = $null
    $assemblyName = $null
    $assemblyVersion = $null
    if ($file.Extension -ieq '.dll') {
        try {
            $identity = [Reflection.AssemblyName]::GetAssemblyName($file.FullName)
            $assemblyName = $identity.Name
            $assemblyVersion = $identity.Version?.ToString()
            $stream = [IO.File]::OpenRead($file.FullName)
            try {
                $pe = [Reflection.PortableExecutable.PEReader]::new($stream)
                try {
                    $metadata = [Reflection.Metadata.PEReaderExtensions]::GetMetadataReader($pe)
                    $mvid = $metadata.GetGuid($metadata.GetModuleDefinition().Mvid).ToString('D')
                } finally { $pe.Dispose() }
            } finally { $stream.Dispose() }
        } catch {
            # Native/resource DLLs have no managed assembly identity.
        }
    }
    $entries.Add([pscustomobject]@{
        Mvid = $mvid
        RelativePath = $relative
        Length = $file.Length
        Sha256 = (Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash
        AssemblyName = $assemblyName
        AssemblyVersion = $assemblyVersion
    })
}

$lines = [Collections.Generic.List[string]]::new()
$lines.Add('// <auto-generated />')
$lines.Add('namespace WinGPUDoctor.Supervisor;')
$lines.Add('')
$lines.Add('internal static class EmbeddedWorkerDeploymentManifest')
$lines.Add('{')
$lines.Add('    internal static WorkerDeploymentManifest Value { get; } = new(new WorkerDeploymentEntry[]')
$lines.Add('    {')
foreach ($entry in $entries) {
    $name = if ($null -eq $entry.AssemblyName) { 'null' } else { Quote-CSharp $entry.AssemblyName }
    $version = if ($null -eq $entry.AssemblyVersion) { 'null' } else { Quote-CSharp $entry.AssemblyVersion }
    $module = if ($null -eq $entry.Mvid) { 'null' } else { Quote-CSharp $entry.Mvid }
    $lines.Add("        new($(Quote-CSharp $entry.RelativePath), $($entry.Length), $(Quote-CSharp $entry.Sha256), $name, $version, $module),")
}
$lines.Add('    });')
$lines.Add('}')
$content = ($lines -join "`n") + "`n"

$outputFull = [IO.Path]::GetFullPath($OutputPath)
$directory = Split-Path -Parent $outputFull
if (!(Test-Path -LiteralPath $directory)) { New-Item -ItemType Directory -Path $directory -Force | Out-Null }
if (Test-Path -LiteralPath $outputFull) {
    $existing = [IO.File]::ReadAllText($outputFull)
    if ($existing -ceq $content) { exit 0 }
}
[IO.File]::WriteAllText($outputFull, $content, [Text.UTF8Encoding]::new($false))
